// first.insertAdjacentHTML('beforebegin', '<div class="test">beforeend</div>')
// first.insertAdjacentHTML('beforeend', '<div class="test">beforeend</div>')
// first.insertAdjacentHTML('beforbegin', '<div class="test">beforeend</div>')
// first.insertAdjacentHTML('beforeend', '<div class="test">beforeend</div>')
first.remove()